## CHANGE this to the name of your plugin.
name: MzTech

## CHANGE this to your username.
author: zhuoyiping

## CHANGE this to a meaninful but short description of your plugin.
description: A simple Slimefun Addon.一个简单的粘液科技附属

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.CHANGEME.slimefunaddon.ExampleAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/zhuoyiping/MzTech-SFAddon

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
